spring:
  application:
    name: 06-Microservices_CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Chaithubuddy/configuration_properties
          clone-on-start: true
